### ISSUE TITLE
이메일 회원가입시 중복된 이메일 제출 후 사용가능한 이메일로 제출하면 정상적으로 회원가입이 진행되지 않는 문제

### ISSUE THREAD

**Issue by xoxojw** [cheddaryeon/NewsFeed#10]
이메일 회원가입시 이메일에 이미 가입된 이메일을 입력하고 회원가입 버튼을 누르면,
error에 Firebase: Error (auth/email-already-in-use)가 출력되고
다시 사용가능한 이메일을 입력해서 가입을 진행하려고 하면 정상적으로 가입이 되지 않는 문제

**Comment by xoxojw** [comment]
팀원들과 화면공유하면서 고민을 나눴더니 마법처럼 해결되었다...
아마 해당 컴포넌트에서 state로 관리하던 error를 set해주는 `setError(false);`를 onSubmit 함수에 추가해줘서 그런 것 같습니다..

**Comment by AJ3504** [comment]
wow.. 공유감사합니다!!!
