### ISSUE TITLE
link태그 대신 버튼 + useNavigate으로 구현했을 때, 페이지 안넘어가는 문제

### ISSUE THREAD

**Issue by AJ3504** [cheddaryeon/NewsFeed#26]

**Comment by AJ3504** [comment]
❗️이 부분 피드백 꼭 부탁드립니다!❗️


❶현재는 115번째 줄에 
`<DetailContentButton to={`/detail/${content.id}`}>
                  결재 검토하기
                </DetailContentButton>`

처럼 링크태그로 구현하였는데,
                
❷얘를 버튼 + onCommentClick() 으로 구현하고 싶어서 다음과 같이 리팩토링 해보았으나 작동이 안됩니다. (페이지가 넘어가지지 않습니다🥲)
<함수 선언부>
`const onCommentClick = (contentId) => {
    if (currentUser) {
      console.log(currentUser) 
      console.log(contentId)
    
      navigate(`/detail/${contentId}`);

    } else {
      alert("로그인 해주세요!");
      // 로그인 창 띄우기 추가
    }
  };`
  
  <함수 실행부>
return (
    <Container>
      <NewContentButton onClick={onAddContentsClick}>
        새로운 결재 요청하기
      </NewContentButton>
      <ul>
        {/* 가져온 DB data 클라이언트쪽에 보여주기 */}
        {contents.map((content) => {
          return (
            <ContentsList>
              <ContentPreview key={content?.id}>
                <p>
                  <span>{content.contentsDate}</span> 결재요청건
                </p>
                <img src={content.downloadURL} alt="이미지 없음" />
                <p>
                  결재 품목 :{" "}
                  <span>
                    {content.wishItemText} ({content.itemPriceText})원에 대한
                    결재요청건이 있습니다.
                  </span>
                </p>

                <p>결재를 검토하시겠습니까?</p>
                <DetailContentButton onClick={() => onCommentClick(content.id)}>
                  결재 검토하기
                </DetailContentButton>
              </ContentPreview>
            </ContentsList>
          );
        })}
      </ul>
      <TopButton onClick={handleScrollToTop}> ▲ </TopButton>
    </Container>
  );

**Comment by AJ3504** [comment]
`const onCommentClick = (contentId) => {
    // navigate("/abc"); //얘도 안됨
    console.log("콘솔콘솔"); //애도 들어오고
    if (currentUser) {
      console.log(currentUser); //얘도 들어오고
      console.log(contentId); //얘도 들어오는데 뭐가 문제지
     
      navigate(`/detail/${contentId}`);

    } else {
      alert("로그인 해주세요!");
      // 로그인 창 띄우기 추가
    }
  };

  //--------------------------------------------------------------------------//
  return (
    <Container>
      <NewContentButton onClick={onAddContentsClick}>
        새로운 결재 요청하기
      </NewContentButton>
      <ul>
        {/* 가져온 DB data 클라이언트쪽에 보여주기 */}
        {contents.map((content) => {
          return (
            <ContentsList>
              <ContentPreview key={content?.id}>
                <p>
                  <span>{content.contentsDate}</span> 결재요청건
                </p>
                <img src={content.downloadURL} alt="이미지 없음" />
                <p>
                  결재 품목 :{" "}
                  <span>
                    {content.wishItemText} ({content.itemPriceText})원에 대한
                    결재요청건이 있습니다.
                  </span>
                </p>

                <p>결재를 검토하시겠습니까?</p>
                <DetailContentButton onClick={() => onCommentClick(content.id)}>
                  결재 검토하기
                </DetailContentButton>
              </ContentPreview>
            </ContentsList>
          );
        })}
      </ul>
      <TopButton onClick={handleScrollToTop}> ▲ </TopButton>
    </Container>
  );
};`

**Comment by AJ3504** [comment]
```const onCommentClick = (contentId) => {
    // navigate("/abc"); //얘도 안됨
    console.log("콘솔콘솔"); //애도 들어오고
    if (currentUser) {
      console.log(currentUser); //얘도 들어오고
      console.log(contentId); //얘도 들어오는데 뭐가 문제지
     
      navigate(`/detail/${contentId}`);

    } else {
      alert("로그인 해주세요!");
      // 로그인 창 띄우기 추가
    }
  };

  //--------------------------------------------------------------------------//
  return (
    <Container>
      <NewContentButton onClick={onAddContentsClick}>
        새로운 결재 요청하기
      </NewContentButton>
      <ul>
        {/* 가져온 DB data 클라이언트쪽에 보여주기 */}
        {contents.map((content) => {
          return (
            <ContentsList>
              <ContentPreview key={content?.id}>
                <p>
                  <span>{content.contentsDate}</span> 결재요청건
                </p>
                <img src={content.downloadURL} alt="이미지 없음" />
                <p>
                  결재 품목 :{" "}
                  <span>
                    {content.wishItemText} ({content.itemPriceText})원에 대한
                    결재요청건이 있습니다.
                  </span>
                </p>

                <p>결재를 검토하시겠습니까?</p>
                <DetailContentButton onClick={() => onCommentClick(content.id)}>
                  결재 검토하기
                </DetailContentButton>
              </ContentPreview>
            </ContentsList>
          );
        })}
      </ul>
      <TopButton onClick={handleScrollToTop}> ▲ </TopButton>
    </Container>
  );
};```

**Comment by AJ3504** [comment]
```  const onCommentClick = (contentId) => {
    // navigate("/abc"); //얘도 안됨
    console.log("콘솔콘솔"); //애도 들어오고
    if (currentUser) {
      console.log(currentUser); //얘도 들어오고
      console.log(contentId); //얘도 들어오는데 뭐가 문제지
     
      navigate(`/detail/${contentId}`);

    } else {
      alert("로그인 해주세요!");
      // 로그인 창 띄우기 추가
    }
  };

  //--------------------------------------------------------------------------//
  return (
    <Container>
      <NewContentButton onClick={onAddContentsClick}>
        새로운 결재 요청하기
      </NewContentButton>
      <ul>
        {/* 가져온 DB data 클라이언트쪽에 보여주기 */}
        {contents.map((content) => {
          return (
            <ContentsList>
              <ContentPreview key={content?.id}>
                <p>
                  <span>{content.contentsDate}</span> 결재요청건
                </p>
                <img src={content.downloadURL} alt="이미지 없음" />
                <p>
                  결재 품목 :{" "}
                  <span>
                    {content.wishItemText} ({content.itemPriceText})원에 대한
                    결재요청건이 있습니다.
                  </span>
                </p>

                <p>결재를 검토하시겠습니까?</p>
                <DetailContentButton onClick={() => onCommentClick(content.id)}>
                  결재 검토하기
                </DetailContentButton>
              </ContentPreview>
            </ContentsList>
          );
        })}
      </ul>
      <TopButton onClick={handleScrollToTop}> ▲ </TopButton>
    </Container>
  );```

**Comment by AJ3504** [comment]
```const onCommentClick = (contentId) => {
    // navigate("/abc"); //얘도 안됨
    console.log("콘솔콘솔"); //애도 들어오고
    if (currentUser) {
      console.log(currentUser); //얘도 들어오고
      console.log(contentId); //얘도 들어오는데 뭐가 문제지
     
      navigate(`/detail/${contentId}`);

    } else {
      alert("로그인 해주세요!");
      // 로그인 창 띄우기 추가
    }
  };```

**Comment by AJ3504** [comment]
``` const onCommentClick = (contentId) => {
    // navigate("/abc"); //얘도 안됨
    console.log("콘솔콘솔"); //애도 들어오고
    if (currentUser) {
      console.log(currentUser); //얘도 들어오고
      console.log(contentId); //얘도 들어오는데 뭐가 문제지
     
      navigate(`/detail/${contentId}`);

    } else {
      alert("로그인 해주세요!");
      // 로그인 창 띄우기 추가
    }
  };

  //--------------------------------------------------------------------------//
  return (
    <Container>
      <NewContentButton onClick={onAddContentsClick}>
        새로운 결재 요청하기
      </NewContentButton>
      <ul>
        {/* 가져온 DB data 클라이언트쪽에 보여주기 */}
        {contents.map((content) => {
          return (
            <ContentsList>
              <ContentPreview key={content?.id}>
                <p>
                  <span>{content.contentsDate}</span> 결재요청건
                </p>
                <img src={content.downloadURL} alt="이미지 없음" />
                <p>
                  결재 품목 :{" "}
                  <span>
                    {content.wishItemText} ({content.itemPriceText})원에 대한
                    결재요청건이 있습니다.
                  </span>
                </p>

                <p>결재를 검토하시겠습니까?</p>
                <DetailContentButton onClick={() => onCommentClick(content.id)}>
                  결재 검토하기
                </DetailContentButton>
              </ContentPreview>
            </ContentsList>
          );
        })}
      </ul>
      <TopButton onClick={handleScrollToTop}> ▲ </TopButton>
    </Container>
  ); ```

**Comment by AJ3504** [comment]
const onCommentClick = (contentId) => {
    // navigate("/abc"); //얘도 안됨
    console.log("콘솔콘솔"); //애도 들어오고
    if (currentUser) {
      console.log(currentUser); //얘도 들어오고
      console.log(contentId); //얘도 들어오는데 뭐가 문제지
     
      navigate(`/detail/${contentId}`);

    } else {
      alert("로그인 해주세요!");
      // 로그인 창 띄우기 추가
    }
  };

  //--------------------------------------------------------------------------//
  return (
    <Container>
      <NewContentButton onClick={onAddContentsClick}>
        새로운 결재 요청하기
      </NewContentButton>
      <ul>
        {/* 가져온 DB data 클라이언트쪽에 보여주기 */}
        {contents.map((content) => {
          return (
            <ContentsList>
              <ContentPreview key={content?.id}>
                <p>
                  <span>{content.contentsDate}</span> 결재요청건
                </p>
                <img src={content.downloadURL} alt="이미지 없음" />
                <p>
                  결재 품목 :{" "}
                  <span>
                    {content.wishItemText} ({content.itemPriceText})원에 대한
                    결재요청건이 있습니다.
                  </span>
                </p>

                <p>결재를 검토하시겠습니까?</p>
                <DetailContentButton onClick={() => onCommentClick(content.id)}>
                  결재 검토하기
                </DetailContentButton>
              </ContentPreview>
            </ContentsList>
          );
        })}
      </ul>
      <TopButton onClick={handleScrollToTop}> ▲ </TopButton>
    </Container>
  );

**Comment by AJ3504** [comment]
const onCommentClick = (contentId) => {
  console.log("콘솔콘솔");
  if (currentUser) {
    console.log(currentUser);
    console.log(contentId);
    navigate(`/detail/${contentId}`);
  } else {
    alert("로그인 해주세요!");
    // 로그인 창 띄우기 추가
  }
};

//--------------------------------------------------------------------------//
return (
  <Container>
    <NewContentButton onClick={onAddContentsClick}>
      새로운 결재 요청하기
    </NewContentButton>
    <ul>
      {contents.map((content) => {
        return (
          <ContentsList key={content?.id}>
            <ContentPreview>
              <p>
                <span>{content.contentsDate}</span> 결재요청건
              </p>
              <img src={content.downloadURL} alt="이미지 없음" />
              <p>
                결재 품목 :{" "}
                <span>
                  {content.wishItemText} ({content.itemPriceText})원에 대한
                  결재요청건이 있습니다.
                </span>
              </p>
              <p>결재를 검토하시겠습니까?</p>
              <DetailContentButton onClick={() => onCommentClick(content.id)}>
                결재 검토하기
              </DetailContentButton>
            </ContentPreview>
          </ContentsList>
        );
      })}
    </ul>
    <TopButton onClick={handleScrollToTop}> ▲ </TopButton>
  </Container>
);

**Comment by AJ3504** [comment]
https://github.com/cheddaryeon/NewsFeed/blob/08263214dc905597539b174b24a020a0960831a8/PreviewContentsList_issue#L1

**Comment by DevelopSoo** [comment]
> ❗️이 부분 피드백 꼭 부탁드립니다!❗️
> 
> ❶현재는 previewContentsList.jsx의 115번째 줄에 `<DetailContentButton to={`/detail/${content.id}`}> 결재 검토하기 </DetailContentButton>`
> 
> 처럼 링크태그로 구현하였는데,
> 
> ❷얘를 버튼 + onCommentClick() 으로 구현하고 싶어서 다음과 같이 리팩토링 해보았으나 작동이 안됩니다. (페이지가 넘어가지지 않습니다🥲)
> 
> 아래에 작동 안되는 코드 공유드리겠습니다!

이 부분은 좀 더 확인해봐야겠네요. 저도 이해가 안되네요...;;

**Comment by AJ3504** [comment]
`
                <button onClick={() => onCommentClick(content.id)}>
                  결재 검토하기
                </button>
 `
                
저도 확인해봤더니, 기존 styled component가 입혀진 DetailContentButton이 아니라 그냥 button태그에 onClick을 걸었더니 (나머지는 동일) 동작이 됩니다!
