### ISSUE TITLE
SignUp.jsx 컴포넌트 파일명 변경 사항이 반영되지 않는 issue

### ISSUE THREAD

**Issue by jiwoniverse** [cheddaryeon/NewsFeed#6]
처음 `Signup.jsx`로 만들었던 컴포넌트를 `SignUp.jsx`로 소문자 -> 대문자로 바꾸어 컴포넌트 파일명을 바꾸었는데, 이 변경사항이 반영되지 않는 issue 발생

**Comment by xoxojw** [comment]
Signup.jsx 삭제 후 재업로드 하여 문제 해결
